const fs = require('fs');
const path = require('path');
const { Api } = require('telegram');
const { extractDeepLinks, generateStartMessage } = require('../utils/linkParser');
const config = require('../config');

const REPORT_FILE = path.resolve(__dirname, '..', config.REPORT_FILE);

/**
 * Random delay antara 3-10 detik
 */
function randomDelay() {
  const delay = Math.floor(Math.random() * (config.MAX_DELAY - config.MIN_DELAY + 1)) + config.MIN_DELAY;
  return new Promise((resolve) => setTimeout(resolve, delay));
}

/**
 * Cek apakah pesan berisi media (foto/video)
 */
function hasMedia(message) {
  if (!message) return false;
  
  // Cek berbagai tipe media
  if (message.media) {
    const mediaType = message.media.className;
    return (
      mediaType === 'MessageMediaPhoto' ||
      mediaType === 'MessageMediaDocument' ||
      mediaType === 'MessageMediaVideo' ||
      mediaType === 'MessageMediaWebPage' ||
      mediaType === 'MessageMediaGeo' ||
      mediaType === 'MessageMediaContact' ||
      mediaType === 'MessageMediaPoll'
    );
  }
  return false;
}

/**
 * Generate report ke report.md
 */
function generateReport(reportData) {
  const report = `# Laporan Deep Link Scraping

---

## Informasi Scraping
- **Channel:** ${reportData.channelUsername || reportData.channelId || 'N/A'}
- **Range Pesan:** ID ${reportData.startId} - ID ${reportData.endId}
- **Tanggal:** ${new Date().toLocaleString('id-ID')}

---

## Statistik

| Metrik | Jumlah |
|--------|--------|
| Total Pesan Discrape | ${reportData.totalMessages} |
| Total Link Ditemukan | ${reportData.totalLinks} |
| Total Media (Foto/Video) | ${reportData.totalMedia} |
| Pesan yang Mengandung Deep Link | ${reportData.deepLinkCount} |
| Response tanpa Media | ${reportData.noMediaCount} |

---

## Detail Link

${reportData.deepLinks.length > 0 ? reportData.deepLinks.map((link, i) => `### ${i + 1}. Link
- **URL:** ${link.fullUrl}
- **Bot:** @${link.botUsername}
- **Start Data:** ${link.startData}
- **Response:** ${link.hasMedia ? '✅ Ada Media' : '❌ Tidak Ada Media'}`).join('\n\n') : '**Tidak ada deep link ditemukan.**'}

---

## Status

${reportData.stopped ? '⚠️ **BOT STOP** - Ditemukan response tanpa media atau dihentikan user (Ctrl+C)' : '✅ **SELESAI** - Semua pesan berhasil discrape'}

---

*Report generated by UserTeleNode Bot*
`;

  fs.writeFileSync(REPORT_FILE, report, 'utf-8');
  console.log(`\n📄 Report telah disimpan ke: ${REPORT_FILE}`);
}

/**
 * Deep Link Scraper
 * @param {TelegramClient} client - Instance Telegram client
 */
async function deepLinkScraper(client, rl) {
  const reportData = {
    channelUsername: '',
    channelId: '',
    startId: 0,
    endId: 0,
    totalMessages: 0,
    totalLinks: 0,
    totalMedia: 0,
    deepLinkCount: 0,
    noMediaCount: 0,
    deepLinks: [],
    stopped: false
  };

  // Safe exit handler
  let isRunning = true;
  
  const safeExit = async () => {
    if (!isRunning) return;
    isRunning = false;
    
    console.log('\n\n⚠️  Menerima sinyal berhenti...');
    console.log('📊 Merangkum laporan...');
    
    reportData.stopped = true;
    generateReport(reportData);
    
    console.log('✅ Laporan telah disimpan.');
    console.log('👋Bot berhenti dengan aman.');
    
    try {
      await client.disconnect();
    } catch (e) {
      // Ignore disconnect errors
    }
    process.exit(0);
  };

  // Register Ctrl+C handler
  process.on('SIGINT', safeExit);
  process.on('SIGTERM', safeExit);

  console.log('\n🔗 Mode Deep Link Scraper');
  console.log('─'.repeat(40));

  // Input channel
  const channelInput = rl.question('Masukkan username/link channel publik (contoh: contohchannel atau https://t.me/contohchannel): ');
  let channelId = channelInput.trim();
  
  // Bersihkan input dari URL
  if (channelId.includes('t.me/')) {
    const match = channelId.match(/t\.me\/([a-zA-Z0-9_]+)/);
    channelId = '@' + (match ? match[1] : channelId);
  } else if (!channelId.startsWith('@')) {
    channelId = '@' + channelId;
  }
  
  console.log(`Target channel: ${channelId}`);
  
  // Cek channel terlebih dahulu
  console.log(`Mengecek channel ${channelId}...`);
  let channel;
  try {
    channel = await client.getEntity(channelId);
  } catch (e) {
    console.error(`❌ Channel ${channelId} tidak ditemukan atau tidak bisa diakses.`);
    console.log('   Pastikan channel publik dan Anda sudah join.');
    process.exit(1);
  }
  
  reportData.channelUsername = channelId;
  reportData.channelId = channel.id ? channel.id.toString() : 'N/A';
  
  console.log(`✅ Channel ditemukan: ${channel.title || channel.username || channelId}`);
  
  // Dapatkan info pesan terakhir
  console.log('\nMendapatkan info pesan terakhir...');
  const messages = await client.getMessages(channel, { limit: 1 });
  if (messages.length === 0) {
    console.log('❌ Tidak ada pesan di channel ini.');
    process.exit(1);
  }
  
  const maxMsgId = messages[0].id;
  console.log(`ID Pesan terakhir: ${maxMsgId}`);
  
  // Input range pesan
  const startInput = rl.question(`Masukkan ID pesan awal (1-${maxMsgId}): `);
  const startId = parseInt(startInput) || 1;
  
  const endInput = rl.question(`Masukkan ID pesan akhir (${startId}-${maxMsgId}): `);
  let endId = parseInt(endInput);
  
  if (isNaN(endId) || endId > maxMsgId) {
    endId = maxMsgId;
  }
  
  if (startId > endId) {
    console.log('❌ ID awal harus lebih kecil dari ID akhir.');
    process.exit(1);
  }
  
  reportData.startId = startId;
  reportData.endId = endId;
  
  console.log('\n' + '='.repeat(40));
  console.log(`🚀 Scraping dimulai...`);
  console.log(`   Channel: ${channelId}`);
  console.log(`   Range: ID ${startId} - ${endId}`);
  console.log(`   Delay: 3-10 detik per pesan`);
  console.log('   Tekan Ctrl+C untuk berhenti dan generate report.');
  console.log('='.repeat(40));
  
  const totalToCheck = endId - startId + 1;
  
  // Proses scraping pesan per pesan
  for (let msgId = startId; msgId <= endId; msgId++) {
    if (!isRunning) return;
    
    const progress = msgId - startId + 1;
    console.log(`\n📥 [${progress}/${totalToCheck}] Mengecek pesan ID: ${msgId}...`);
    
    try {
      // Ambil pesan spesifik - GramJS expects array of message IDs
      const msgs = await client.getMessages(channel, { ids: [msgId] });
      
      // Jika tidak ada pesan di ID tersebut
      if (!msgs || (Array.isArray(msgs) && msgs.length === 0)) {
        console.log(`   ⏭️  Tidak ada pesan di ID ${msgId}.`);
        continue;
      }
      
      // Handle jika return bukan array
      const message = Array.isArray(msgs) ? msgs[0] : msgs;
      if (!message) continue;
      
      reportData.totalMessages++;
      
      // Cek media di pesan channel
      if (hasMedia(message)) {
        reportData.totalMedia++;
        console.log(`   🖼️  Pesan mengandung media.`);
      }
      
      // Cek apakah pesan mengandung text
      const messageText = message.text || '';
      if (messageText) {
        console.log(`   📝 Text: ${messageText.substring(0, 100)}${messageText.length > 100 ? '...' : ''}`);
      }
      
      // Parse deep links
      const deepLinks = extractDeepLinks(messageText);
      
      if (deepLinks.length > 0) {
        console.log(`   🔗 Ditemukan ${deepLinks.length} deep link!`);
        reportData.totalLinks += deepLinks.length;
        
        // Proses setiap deep link
        for (const link of deepLinks) {
          reportData.deepLinkCount++;
          console.log(`   ↳ Bot: @${link.botUsername}`);
          console.log(`   ↳ Start Data: ${link.startData}`);
          
          // Cari entity bot
          let botPeer;
          try {
            botPeer = await client.getEntity(link.botUsername);
            console.log(`   ✅ Bot ditemukan: ${botPeer.firstName || botPeer.username}`);
          } catch (e) {
            console.log(`   ⚠️ Bot @${link.botUsername} tidak ditemukan. Skip.`);
            continue;
          }
          
          // Kirim /start
          const startMessage = generateStartMessage(link.botUsername, link.startData);
          console.log(`   📤 Mengirim: ${startMessage}`);
          
          try {
            await client.sendMessage(botPeer, { message: startMessage });
            
            // Tunggu response dari bot
            console.log(`   ⏳ Menunggu response dari bot...`);
            await randomDelay();
            
            // Ambil pesan terakhir dari bot - pastikan ambil pesan SETELAH kita kirim /start
            try {
              const botMessages = await client.getMessages(botPeer, { limit: 5 });
              // Filter pesan yang dikirim SETELAH kita kirim /start (dalam 30 detik terakhir)
              const now = Date.now();
              const recentMessages = botMessages.filter(msg => {
                const msgDate = msg.date ? new Date(msg.date).getTime() : 0;
                return (now - msgDate) < 60000; // pesan dalam 1 menit terakhir
              });
              
              const response = recentMessages.length > 0 ? recentMessages[0] : (botMessages.length > 0 ? botMessages[0] : null);
              if (response) {
                const hasMediaResponse = hasMedia(response);
                
                link.hasMedia = hasMediaResponse;
                
                if (hasMediaResponse) {
                  console.log(`   ✅ Bot response dengan media.`);
                  reportData.totalMedia++;
                } else {
                  console.log(`   ❌ Bot response TANPA media!`);
                  console.log(`   Response text: ${(response.text || 'N/A').substring(0, 100)}`);
                  
                  reportData.noMediaCount++;
                  
                  // Bot harus stop jika tidak ada media
                  console.log('\n' + '='.repeat(40));
                  console.log('⛔ BOT STOP - Response bot tidak mengandung media!');
                  console.log('='.repeat(40));
                  
                  isRunning = false;
                  reportData.stopped = true;
                  
                  // Remove Ctrl+C listeners untuk tidak double exit
                  process.removeAllListeners('SIGINT');
                  process.removeAllListeners('SIGTERM');
                  
                  generateReport(reportData);
                  
                  try {
                    await client.disconnect();
                  } catch (e) {}
                  
                  rl.close();
                  process.exit(0);
                }
              } else {
                console.log(`   ⚠️ Tidak ada response dari bot.`);
                link.hasMedia = false;
              }
            } catch (e) {
              console.log(`   ⚠️ Gagal cek response bot: ${e.message}`);
              link.hasMedia = false;
            }
          } catch (e) {
            console.log(`   ❌ Gagal kirim /start ke bot: ${e.message}`);
            link.hasMedia = false;
          }
          reportData.deepLinks.push(link);
        }
      }
      
    } catch (e) {
      console.log(`   ❌ Error: ${e.message}`);
      
      // Cek flood wait - GramJS format: "A wait of X seconds is required" atau "FloodWaitError"
      const floodMatch = e.message.match(/wait of (\d+)/) || e.message.match(/FLOOD_WAIT_(\d+)/) || e.message.match(/FloodWait/);
      if (floodMatch) {
        const waitTime = floodMatch[1] ? parseInt(floodMatch[1]) : 30;
        console.log(`   ⏳ Flood wait detected. Tunggu ${waitTime} detik...`);
        await new Promise(r => setTimeout(r, waitTime * 1000));
        continue;
      }
    }
    
    // Delay sebelum pesan berikutnya (human-like behavior)
    if (msgId < endId && isRunning) {
      const delay = Math.floor(Math.random() * (config.MAX_DELAY - config.MIN_DELAY + 1)) + config.MIN_DELAY;
      console.log(`   ⏳ Delay ${delay/1000} detik (menghindari rate limit)...`);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }
  
  // Selesai scraping
  if (isRunning) {
    console.log('\n' + '='.repeat(40));
    console.log('✅ Scraping selesai!');
    generateReport(reportData);
  }
  
  // Remove listeners
  process.removeAllListeners('SIGINT');
  process.removeAllListeners('SIGTERM');
  
  rl.close();
  
  try {
    await client.disconnect();
  } catch (e) {}
  
  process.exit(0);
}

module.exports = deepLinkScraper;