const fs = require('fs');
const path = require('path');
const { extractDeepLinks, generateStartMessage } = require('../utils/linkParser');
const { updateHistory, getAllChannels, getLastScrapedId, updateLastScrapedId, updateLastMessageId } = require('../utils/scrapingHistory');
const config = require('../config');

const reportFileName = (typeof config.REPORT_FILE === 'string' && config.REPORT_FILE.trim()) ? config.REPORT_FILE : 'report.md';
const REPORT_FILE = path.resolve(__dirname, '..', reportFileName);

/**
 * Random delay antara konfigurasi MIN_DELAY-MAX_DELAY
 */
function randomDelay() {
  const minDelay = typeof config.MIN_DELAY === 'number' && !isNaN(config.MIN_DELAY) ? config.MIN_DELAY : 3000;
  const maxDelay = typeof config.MAX_DELAY === 'number' && !isNaN(config.MAX_DELAY) ? config.MAX_DELAY : 10000;
  const effectiveMin = Math.min(minDelay, maxDelay);
  const effectiveMax = Math.max(minDelay, maxDelay);
  const delay = Math.floor(Math.random() * (effectiveMax - effectiveMin + 1)) + effectiveMin;
  return new Promise((resolve) => setTimeout(() => resolve(delay), delay));
}

/**
 * Cek apakah pesan berisi media (foto/video)
 */
function hasMedia(message) {
  if (!message) return false;
  
  if (message.media) {
    const mediaType = message.media.className;
    return (
      mediaType === 'MessageMediaPhoto' ||
      mediaType === 'MessageMediaDocument' ||
      mediaType === 'MessageMediaVideo' ||
      mediaType === 'MessageMediaWebPage' ||
      mediaType === 'MessageMediaGeo' ||
      mediaType === 'MessageMediaContact' ||
      mediaType === 'MessageMediaPoll'
    );
  }
  return false;
}

/**
 * Escape HTML special characters to prevent HTML injection in report
 * Also escape markdown special characters for safe display
 */
function escapeForReport(str) {
  if (!str) return '';
  let escaped = String(str).replace(/[*_\[\]()~>#+\-=|{}.!]/g, '\\$&');
  escaped = escaped
    .replace(/&/g, '\u0026amp;')
    .replace(/</g, '\u0026lt;')
    .replace(/>/g, '\u0026gt;')
    .replace(/"/g, '\u0026quot;')
    .replace(/`/g, '\\`');
  return escaped;
}

/**
 * Generate report ke report.md
 */
function generateReport(reportData) {
  const report = `# Laporan Deep Link Scraping

---

## Informasi Scraping
- **Channel:** ${reportData.channelUsername || reportData.channelId || 'N/A'}
- **Range Pesan:** ID ${reportData.startId} - ID ${reportData.endId}
- **Tanggal:** ${new Date().toLocaleString('id-ID')}

---

## Statistik

| Metrik | Jumlah |
|--------|--------|
| Total Pesan Discrape | ${reportData.totalMessages} |
| Total Link Ditemukan | ${reportData.totalLinks} |
| Total Media (Foto/Video) | ${reportData.totalMedia} |
| Pesan yang Mengandung Deep Link | ${reportData.deepLinks.length} |
| Response tanpa Media | ${reportData.noMediaCount} |

---

## Detail Link

${reportData.deepLinks.length > 0 ? reportData.deepLinks.map((link, i) => `### ${i + 1}. Link
- **URL:** \`${escapeForReport(link.fullUrl)}\`
- **Bot:** @${escapeForReport(link.botUsername)}
- **Start Data:** \`${escapeForReport(link.startData)}\`
- **Response:** ${link.hasMedia ? '\u2705 Ada Media' : '\u274c Tidak Ada Media'}`).join('\n\n') : '**Tidak ada deep link ditemukan.**'}

---

## Status

${reportData.stopped ? '\u26a0\ufe0f **BOT STOP** - Ditemukan response tanpa media atau dihentikan user (Ctrl+C)' : '\u2705 **SELESAI** - Semua pesan berhasil discrape'}

---

*Report generated by UserTeleNode Bot*
`;

  fs.writeFileSync(REPORT_FILE, report, 'utf-8');
  console.log(`\n\u{1F4C4} Report telah disimpan ke: ${REPORT_FILE}`);
}

/**
 * Parse channel input to get proper entity identifier
 * Supports: @username, numeric ID (-100...), and t.me URLs
 * @param {string} input - Raw user input
 * @returns {string|number} Channel identifier suitable for getEntity
 */
function parseChannelInput(input) {
  if (!input) return null;
  
  let cleaned = String(input).trim();
  
  if (!cleaned) return null;
  
  // Handle t.me URLs
  if (cleaned.includes('t.me/')) {
    const match = cleaned.match(/t\.me\/([a-zA-Z0-9_]+)/);
    if (match) {
      cleaned = match[1];
    } else {
      const altMatch = cleaned.match(/t\.me\/(.+)/);
      cleaned = altMatch ? altMatch[1] : cleaned;
    }
    cleaned = cleaned.trim();
  }
  
  if (!cleaned) return null;
  
  // Check if it's a numeric channel ID (all digits with optional - prefix)
  const isNumericId = /^-?\d+$/.test(cleaned);
  
  if (isNumericId) {
    return parseInt(cleaned, 10);
  }
  
  if (!cleaned.startsWith('@')) {
    cleaned = '@' + cleaned;
  }
  
  return cleaned;
}

/**
 * Resolve channel entity from parsed ID with fallback handling
 * Specifically handles -100... channel IDs that may fail with standard getEntity
 * @param {TelegramClient} client - GramJS client
 * @param {string|number} parsedChannelId - Parsed channel identifier
 * @returns {Promise<Channel>} Resolved channel entity
 */
async function resolveChannelEntity(client, parsedChannelId) {
  // First, try standard getEntity
  try {
    return await client.getEntity(parsedChannelId);
  } catch (e) {
    // If getEntity fails and we have a numeric ID (especially -100...), use specialized resolution
    if (typeof parsedChannelId === 'number') {
      console.log(`   \u26A0\uFE0F getEntity gagal untuk numeric ID ${parsedChannelId}, mencoba resolusi khusus...`);
      console.log(`   Error: ${e.message}`);
      
      const idStr = String(parsedChannelId);
      let channelIdNum;
      
      // Extract actual channel ID from -100 prefix (Telegram channel encoding)
      // In Telegram: -100xxxxx means channel with internal ID = xxxx
      if (idStr.startsWith('-100')) {
        channelIdNum = parseInt(idStr.substring(4), 10);
      } else if (idStr.startsWith('-')) {
        channelIdNum = parseInt(idStr.substring(1), 10);
      } else {
        channelIdNum = parsedChannelId;
      }
      
      // Try to get the channel via alternative methods
      // Method 1: Try using the constructed peer
      try {
        // The channel ID we extracted might already be the right one
        // Use getEntity with the positive channel ID
        const positiveId = channelIdNum;
        console.log(`   Mencoba dengan channel ID positif: ${positiveId}`);
        return await client.getEntity(positiveId);
      } catch (e2) {
        console.log(`   \u26A0\uFE0F Metode 1 gagal: ${e2.message}`);
      }
      
      // Method 2: Try with explicitly constructed InputPeerChannel
      try {
        console.log(`   Mencoba InputPeerChannel dengan channelId=${channelIdNum}`);
        // We need accessHash, but we can try getting it from existing known entities
        // or by using getFullChannel if we can construct the peer
        const inputPeerChannel = {
          _: 'inputPeerChannel',
          channelId: channelIdNum,
          accessHash: 0n
        };
        return await client.getEntity(inputPeerChannel);
      } catch (e2) {
        console.log(`   \u26A0\uFE0F Metode 2 gagal: ${e2.message}`);
        
        // Final fallback: provide helpful error
        console.error(`\n\u274C Channel dengan ID ${parsedChannelId} tidak dapat diakses.`);
        console.log('\n   \u2139\uFE0F  Kemungkinan penyebab:');
        console.log('   • Anda bukan anggota channel tersebut');
        console.log('   • Channel bersifat private');
        console.log('   • ID channel tidak valid');
        console.log('   •Bot membutuhkan username channel (tanpa -100) sebagai gantinya');
        console.log('\n   💡 Saran: Coba gunakan username channel (contoh: @channelname)');
        console.log('   untuk menghindari masalah dengan format -100...');
        
        throw new Error(`Channel ${parsedChannelId} tidak dapat diakses`);
      }
    } else {
      // For usernames, re-throw original error
      throw e;
    }
  }
}

/**
 * Fetch the latest message ID for a channel from Telegram.
 * Returns null when channel is unavailable or has no messages.
 */
async function fetchLatestMessageId(client, channelName) {
  const parsedChannelId = parseChannelInput(channelName);
  if (!parsedChannelId) {
    return { latestMessageId: null, error: 'Invalid channel name' };
  }

  try {
    const channel = await client.getEntity(parsedChannelId);
    const messages = await client.getMessages(channel, { limit: 1 });
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return { latestMessageId: null, error: 'Tidak ada pesan' };
    }
    return { latestMessageId: messages[0].id, error: null };
  } catch (error) {
    return { latestMessageId: null, error: error.message || 'Tidak dapat diakses' };
  }
}

/**
 * Deep Link Scraper
 * @param {TelegramClient} client - Instance Telegram client
 */
async function deepLinkScraper(client, rl) {
  const reportData = {
    channelUsername: '',
    channelId: '',
    parsedChannelId: '',
    startId: 0,
    endId: 0,
    totalMessages: 0,
    totalLinks: 0,
    totalMedia: 0,
    noMediaCount: 0,
    deepLinks: [],
    stopped: false
  };

  let isRunning = true;
  let lastStartTimestamp = 0;
  let lastProcessedId = 0; // ✅ Track ID terakhir yang berhasil diproses secara realtime

  const safeExit = async () => {
    if (!isRunning) return;
    isRunning = false;
    
    console.log('\n\n\u26A0\uFE0F  Menerima sinyal berhenti...');
    console.log('\u{1F4CA} Merangkum laporan...');

    reportData.stopped = true;
    if (lastProcessedId > 0) {
      reportData.endId = lastProcessedId; // ✅ Fix: Gunakan ID terakhir yang sebenarnya diproses
    }
    generateReport(reportData);

    // Update scraping history if IDs are set
    if (reportData.startId > 0 && lastProcessedId > 0) {
      updateHistory(reportData.parsedChannelId, reportData.startId, lastProcessedId, reportData.deepLinks.length, true);
    }

    console.log('\u2705 Laporan telah disimpan.');
    console.log('\u{1F44B} Bot berhenti dengan aman.');
    
    try {
      await client.disconnect();
    } catch (e) {}

    process.removeListener('SIGINT', safeExit);
    process.removeListener('SIGTERM', safeExit);
    
    // ✅ Pastikan proses exit dengan aman setelah semua operasi IO selesai
    setTimeout(() => process.exit(0), 500);
  };

  process.on('SIGINT', safeExit);
  process.on('SIGTERM', safeExit);

  console.log('\n\u{1F517} Mode Deep Link Scraper');
  console.log('\u2500'.repeat(40));

  if (typeof rl?.question !== 'function') {
    console.error('\u274C Interface readline tidak tersedia.');
    process.exit(1);
  }

  // Tampilkan daftar channel history
  const savedChannels = getAllChannels();
  let channelCache = [];
    // Function to format relative time in Indonesian
    const formatRelativeTime = (date) => {
      const now = new Date();
      const diffMs = now - date;
      const diffSec = Math.floor(diffMs / 1000);
      const diffMin = Math.floor(diffSec / 60);
      const diffHour = Math.floor(diffMin / 60);
      const diffDay = Math.floor(diffHour / 24);

      if (diffSec < 60) return 'baru saja';
      if (diffMin < 60) return `${diffMin} menit yang lalu`;
      if (diffHour < 24) return `${diffHour} jam yang lalu`;
      if (diffDay < 7) return `${diffDay} hari yang lalu`;
      if (diffDay < 30) return `${Math.floor(diffDay / 7)} minggu yang lalu`;
      if (diffDay < 365) return `${Math.floor(diffDay / 30)} bulan yang lalu`;
      return `${Math.floor(diffDay / 365)} tahun yang lalu`;
    };

    console.log('🔄 Checking latest message IDs for all channels...');
    const now = new Date();
    const CACHE_TTL = 60 * 60 * 1000; // 1 hour in milliseconds

    for (const ch of savedChannels) {
      const cachedTimestamp = ch.lastMessageTimestamp ? new Date(ch.lastMessageTimestamp) : null;
      const isCacheValid = cachedTimestamp && (now - cachedTimestamp) < CACHE_TTL;

      if (isCacheValid) {
        // Use cached data
        channelCache.push({
          channelId: null, // Not fetched
          channelName: ch.channelName,
          lastMessageId: ch.lastMessageId,
          lastScrapedId: ch.lastScrapedId,
          lastMessageTimestamp: ch.lastMessageTimestamp,
          status: ch.lastMessageId ? 'Punya pesan (cache)' : 'Kosong (cache)'
        });
        console.log(`📋 Used cache for ${ch.channelName}: ID ${ch.lastMessageId || 'N/A'}`);
      } else {
        // Fetch from API
        try {
          const entity = await client.getEntity(parseChannelInput(ch.channelName));
          const messages = await client.getMessages(entity, { limit: 1 });
          const msg = messages.length > 0 ? messages[0] : null;
          const messageId = msg ? msg.id : null;
          const messageTimestamp = msg ? msg.date : null;

          channelCache.push({
            channelId: entity.id,
            channelName: ch.channelName,
            lastMessageId: messageId,
            lastScrapedId: ch.lastScrapedId,
            lastMessageTimestamp: messageTimestamp,
            status: msg ? 'Punya pesan' : 'Kosong'
          });

          // Update cache
          updateLastMessageId(ch.channelName, messageId, messageTimestamp ? new Date(messageTimestamp * 1000).toISOString() : null);

          console.log(`✅ Checked ${ch.channelName}: ${msg ? `ID ${msg.id}` : 'Kosong'}`);
        } catch (e) {
          let status = 'Tidak dapat diakses';
          if (e.message && e.message.includes('TIMEOUT')) {
            status = 'Timeout';
          }
          channelCache.push({
            channelId: null,
            channelName: ch.channelName,
            lastMessageId: null,
            lastScrapedId: ch.lastScrapedId,
            lastMessageTimestamp: null,
            status: status
          });
          console.log(`❌ Failed to check ${ch.channelName}: ${e.message}`);
        }
      }
      // Increased delay to avoid rate limit
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
        channelCache.push({
          channelId: null,
          channelName: ch.channelName,
          lastMessageId: null,
          lastScrapedId: ch.lastScrapedId,
          lastMessageTimestamp: null,
          status: status
        });
        console.log(`❌ Failed to check ${ch.channelName}: ${e.message}`);
      }
      // Increased delay to avoid rate limit
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    // Sort cache by lastMessageTimestamp descending (nulls last)
    channelCache.sort((a, b) => {
      if (a.lastMessageTimestamp && b.lastMessageTimestamp) {
        return b.lastMessageTimestamp - a.lastMessageTimestamp;
      }
      if (a.lastMessageTimestamp) return -1;
      if (b.lastMessageTimestamp) return 1;
      return 0;
    });

    console.log('\n📋 Daftar channel yang tersedia:');

    // Calculate column widths
    const noWidth = Math.max(2, String(channelCache.length).length);
    const nameWidth = Math.max(7, Math.max(...channelCache.map(ch => ch.channelName.length)));
    const idWidth = Math.max(15, Math.max(...channelCache.map(ch => ch.lastMessageId ? String(ch.lastMessageId).length : 3))); // "N/A" is 3
    const scrapedIdWidth = Math.max(15, Math.max(...channelCache.map(ch => String(ch.lastScrapedId).length)));
    const timeWidth = 40; // For formatted time + relative
    const statusWidth = Math.max(6, Math.max(...channelCache.map(ch => ch.status.length)));

    // Helper function to pad string
    const pad = (str, width, align = 'left') => {
      str = String(str);
      if (str.length > width) {
        str = str.substring(0, width);
      }
      if (align === 'right') {
        return str.padStart(width);
      } else if (align === 'center') {
        const totalPad = width - str.length;
        const leftPad = Math.floor(totalPad / 2);
        const rightPad = totalPad - leftPad;
        return ' '.repeat(leftPad) + str + ' '.repeat(rightPad);
      } else {
        return str.padEnd(width);
      }
    };

    // Table header
    const separator = '+' + '-'.repeat(noWidth + 2) + '+' + '-'.repeat(nameWidth + 2) + '+' + '-'.repeat(idWidth + 2) + '+' + '-'.repeat(scrapedIdWidth + 2) + '+' + '-'.repeat(timeWidth + 2) + '+' + '-'.repeat(statusWidth + 2) + '+';
    const header = '| ' + pad('No', noWidth, 'center') + ' | ' + pad('Channel', nameWidth, 'center') + ' | ' + pad('Last Scraped ID', scrapedIdWidth, 'center') + ' | ' + pad('Last Message ID', idWidth, 'center') + ' | ' + pad('Last Message Time', timeWidth, 'center') + ' | ' + pad('Status', statusWidth, 'center') + ' |';

    console.log(separator);
    console.log(header);
    console.log(separator);

    // Table rows
    channelCache.forEach((ch, idx) => {
      let timeStr;
      if (ch.lastMessageTimestamp) {
        const date = new Date(ch.lastMessageTimestamp * 1000); // Telegram timestamps are in seconds
        const dateTimeStr = date.toLocaleString('id-ID', {
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit'
        });
        const relative = formatRelativeTime(date);
        timeStr = `${dateTimeStr} (${relative})`;
      } else {
        timeStr = 'N/A';
      }
      const idStr = ch.lastMessageId !== null ? String(ch.lastMessageId) : 'N/A';
      const scrapedIdStr = String(ch.lastScrapedId);
      const row = '| ' + pad(idx + 1, noWidth, 'center') + ' | ' + pad(ch.channelName, nameWidth) + ' | ' + pad(scrapedIdStr, scrapedIdWidth, 'right') + ' | ' + pad(idStr, idWidth, 'right') + ' | ' + pad(timeStr, timeWidth) + ' | ' + pad(ch.status, statusWidth, 'center') + ' |';
      console.log(row);
    });

    console.log(separator);
    console.log('\n💡 Masukkan nomor dari daftar, atau input channel baru');

  let channelInput = rl.question('\nMasukkan channel: ').trim();
  let parsedChannelId;

  if (channelInput === '') {
    console.log('❌ Channel tidak boleh kosong');
    process.exit(1);
  }

  // Cek apakah input adalah nomor dari daftar
  if (/^\d+$/.test(channelInput.trim())) {
    const num = parseInt(channelInput);
    if (num >= 1 && num <= channelCache.length) {
      const selectedChannel = channelCache[num - 1];
      parsedChannelId = parseChannelInput(selectedChannel.channelName);
      reportData.startId = selectedChannel.lastMessageId || 0; // Use latest message ID as start
      console.log(`✅ Memilih channel: ${selectedChannel.channelName}`);
      console.log(`   Status: ${selectedChannel.status}`);
      console.log(`   Last Message ID: ${selectedChannel.lastMessageId || 'Tidak ada'}`);
      if (selectedChannel.status !== 'Punya pesan') {
        console.log('⚠️  Peringatan: Channel ini tidak dapat diakses. Proses scraping mungkin gagal.');
      }
    } else {
      console.log('❌ Nomor channel tidak ada di daftar. Silakan masukkan channel secara manual.');
      channelInput = rl.question('\nMasukkan channel baru: ').trim();
      if (channelInput === '') {
        console.log('❌ Channel tidak boleh kosong');
        process.exit(1);
      }
      parsedChannelId = parseChannelInput(channelInput);
    }
  } else {
    parsedChannelId = parseChannelInput(channelInput);
  }

  if (!parsedChannelId) {
    console.error('\u274C Channel tidak boleh kosong.');
    console.log('   Masukkan username atau link channel yang valid.');
    process.exit(1);
  }

  reportData.parsedChannelId = parsedChannelId;
  
  console.log(`Target channel: ${parsedChannelId}`);
  
  // Cek channel terlebih dahulu
  console.log(`Mengecek channel ${parsedChannelId}...`);
  let channel;
  
  try {
    // Use the specialized resolver with fallback
    channel = await resolveChannelEntity(client, parsedChannelId);
  } catch (e) {
    console.error(`\u274C Channel ${parsedChannelId} tidak ditemukan atau tidak bisa diakses.`);
    console.log(`   Error: ${e.message}`);
    process.exit(1);
  }
  
  // Store channel info
  reportData.channelUsername = channel.username ? `@${channel.username}` : (typeof parsedChannelId === 'string' ? parsedChannelId : '');
  reportData.channelId = channel.id ? channel.id.toString() : (typeof parsedChannelId === 'number' ? parsedChannelId.toString() : 'N/A');
  
  console.log(`\u2705 Channel ditemukan: ${channel.title || channel.username || channel.id}`);
  
  // Dapatkan info pesan terakhir
  console.log('\nMendapatkan info pesan terakhir...');
  const messages = await client.getMessages(channel, { limit: 1 });
  if (!messages || !Array.isArray(messages) || messages.length === 0) {
    console.log('\u274C Tidak ada pesan di channel ini.');
    process.exit(1);
  }
   
  const maxMsgId = messages[0].id;
  console.log(`ID Pesan terakhir: ${maxMsgId}`);

  // Cek apakah ada history untuk channel ini
  const lastScrapedId = getLastScrapedId(parsedChannelId);
  let defaultStartId = 1;
  if (lastScrapedId) {
    defaultStartId = lastScrapedId + 1;
    console.log(`\n✅ ID terakhir yang discrape dari history: ${lastScrapedId}`);
    if (lastScrapedId >= maxMsgId) {
      console.log(`ℹ️ Semua pesan di channel sudah discrape sampai ID terbaru ${maxMsgId}`);
      console.log(`✅ Tidak ada pesan baru yang perlu discrape`);
      process.exit(0);
    }
    console.log(`   Terdapat ${maxMsgId - lastScrapedId} pesan baru sejak terakhir discrape.`);
    console.log(`👉 Default akan lanjut dari ID ${defaultStartId}`);
  } else {
    console.log('\nℹ️ Channel ini belum pernah discrape sebelumnya');
  }
  
  // Input range pesan with guards
  const startInput = rl.question(`\nMasukkan ID pesan awal (default: ${defaultStartId}): `).trim();
  let startId = parseInt(String(startInput), 10);
  
  if (isNaN(startId) || startId < 1 || startId > maxMsgId) {
    startId = defaultStartId;
  }
  
  // ✅ Warning jika user input ID dibawah history yang ada
  if (lastScrapedId && startId <= lastScrapedId) {
    console.log(`\n⚠️  PERINGATAN: ID ${startId} sudah pernah di scrape sebelumnya`);
    console.log(`   Ini akan menyebabkan scrape ulang pesan yang sudah diproses`);
  }
  
  const endInput = rl.question(`Masukkan ID pesan akhir (default: ${maxMsgId}): `).trim();
  let endId = parseInt(String(endInput), 10);
  
  if (isNaN(endId) || endId < startId || endId > maxMsgId) {
    endId = maxMsgId;
  }
  
  console.log(`\n✅ Range yang dipilih: ID ${startId} - ${endId}`);
  
  reportData.startId = startId;
  reportData.endId = endId;
  
  console.log('\n' + '='.repeat(40));
  console.log(`\u{1F680} Scraping dimulai...`);
  console.log(`   Channel: ${parsedChannelId}`);
  console.log(`   Range: ID ${startId} - ${endId}`);
  const minSec = (typeof config.MIN_DELAY === 'number' ? config.MIN_DELAY : 3000) / 1000;
  const maxSec = (typeof config.MAX_DELAY === 'number' ? config.MAX_DELAY : 10000) / 1000;
  console.log(`   Delay: ${minSec.toFixed(1)}-${maxSec.toFixed(1)} detik per pesan`);
  console.log('   Tekan Ctrl+C untuk berhenti dan generate report.');
  console.log('='.repeat(40));
  
  const totalToCheck = endId - startId + 1;

  if (totalToCheck <= 0) {
    console.log('\n❌ Range ID tidak valid');
    process.exit(1);
  }
  
  console.log(`\n✅ Akan memproses ${totalToCheck} pesan`);

  // ✅ Validasi konfigurasi delay
  if (typeof config.MIN_DELAY !== 'number' || config.MIN_DELAY < 0) {
    console.log('\n⚠️  MIN_DELAY tidak valid, menggunakan default 3000ms');
    config.MIN_DELAY = 3000;
  }
  if (typeof config.MAX_DELAY !== 'number' || config.MAX_DELAY < config.MIN_DELAY) {
    console.log('\n⚠️  MAX_DELAY tidak valid, menggunakan default 10000ms');
    config.MAX_DELAY = 10000;
  }
  
  for (let msgId = startId; msgId <= endId && isRunning; msgId++) {
    
      const progress = msgId - startId + 1;
      console.log(`\n\u{1F4E5} [${progress}/${totalToCheck}] Mengecek pesan ID: ${msgId}...`);
    
    try {
      const msgs = await client.getMessages(channel, { ids: [msgId] });
      
      if (!msgs || !Array.isArray(msgs) || msgs.length === 0) {
        console.log(`   \u23ED\uFE0F  Tidak ada pesan di ID ${msgId}.`);
        continue;
      }
      
      const message = msgs[0];
      if (!message || !message.id) {
        console.log(`   \u23ED\uFE0F  Pesan tidak valid di ID ${msgId}.`);
        // ✅ Tetap update ID terakhir bahkan jika pesan kosong / tidak valid
        lastProcessedId = msgId;
        continue;
      }
      
      reportData.totalMessages++;
      lastProcessedId = msgId; // ✅ Update HANYA setelah pesan BERHASIL di proses
      
      if (hasMedia(message)) {
        reportData.totalMedia++;
        console.log(`   \u{1F5BC}\uFE0F  Pesan mengandung media.`);
      }
      
      const messageText = message.text || '';
      if (messageText) {
        console.log(`   \u{1F4DD} Text: ${messageText.substring(0, 100)}${messageText.length > 100 ? '...' : ''}`);
      }
      
      const deepLinks = extractDeepLinks(messageText);
      
      if (deepLinks.length > 0) {
        console.log(`   \u{1F517} Ditemukan ${deepLinks.length} deep link!`);
        reportData.totalLinks += deepLinks.length;
        
        for (const link of deepLinks) {
          console.log(`   \u21B3 Bot: @${link.botUsername}`);
          console.log(`   \u21B3 Start Data: ${link.startData}`);
          
          let botPeer;
          try {
            botPeer = await client.getEntity(link.botUsername);
            console.log(`   \u2705 Bot ditemukan: ${botPeer.firstName || botPeer.username}`);
          } catch (e) {
            console.log(`   \u26A0\uFE0F Bot @${link.botUsername} tidak ditemukan. Skip.`);
            continue;
          }
          
          const startMessage = generateStartMessage(link.botUsername, link.startData);
          console.log(`   \u{1F4E4} Mengirim: ${startMessage}`);
          
          try {
            await client.sendMessage(botPeer, { message: startMessage });
            lastStartTimestamp = Date.now();
            console.log(`   \u23F3 Menunggu response dari bot...`);
            
            try {
              const botMessages = await client.getMessages(botPeer, { limit: 5 });
              if (!botMessages || !Array.isArray(botMessages)) {
                botMessages = [];
              }
              
              const recentMessages = botMessages.filter(msg => {
                if (!msg || !msg.date) return false;
                const msgTimestamp = typeof msg.date === 'number' ? msg.date * 1000 : new Date(msg.date).getTime();
                const isAfterStart = msgTimestamp > lastStartTimestamp;
                const senderId = msg.fromId ? (msg.fromId.userId || msg.fromId.channelId || msg.fromId.chatId) : null;
                const isFromBot = senderId && senderId.toString() === botPeer.id.toString();
                return isAfterStart && isFromBot;
              });
              
              const response = recentMessages.length > 0 ? recentMessages[0] : null;
              
              if (response) {
                const hasMediaResponse = hasMedia(response);
                link.hasMedia = hasMediaResponse;
                
                if (hasMediaResponse) {
                  console.log(`   \u2705 Bot response dengan media.`);
                  reportData.totalMedia++;
                } else {
                  console.log(`   \u274C Bot response TANPA media!`);
                  console.log(`   Response text: ${(response.text || 'N/A').substring(0, 100)}`);
                  
                  reportData.noMediaCount++;
                  
                  console.log('\n' + '='.repeat(40));
                  console.log('\u26D4 BOT STOP - Response bot tidak mengandung media!');
                  console.log('='.repeat(40));
                  
                  // ✅ Update ID terakhir SEBELUM exit
                  lastProcessedId = msgId;

                  isRunning = false;
                  reportData.stopped = true;
                  reportData.endId = msgId;
                  link.hasMedia = false;
                  reportData.deepLinks.push(link);

                  // ✅ Gunakan safeExit untuk exit secara aman dan konsisten
                  safeExit();
                  return;
                }
              } else {
                console.log(`   \u26A0\uFE0F Tidak ada response dari bot.`);
                link.hasMedia = false;
              }
            } catch (e) {
              console.log(`   \u26A0\uFE0F Gagal cek response bot: ${e.message}`);
              link.hasMedia = false;
            }
            
            if (!reportData.stopped) {
              reportData.deepLinks.push(link);
            }
            
          } catch (e) {
            console.log(`   \u274C Gagal kirim /start ke bot: ${e.message}`);
            link.hasMedia = false;
            reportData.deepLinks.push(link);
          }
        }
      }
      
      
    } catch (e) {
      console.log(`   \u274C Error: ${e.message}`);
      
      const floodMatch = e.message.match(/wait of ([\d.]+)/) || 
                         e.message.match(/FLOOD_WAIT_([\d.]+)/) || 
                         e.message.match(/FloodWait/);
      if (floodMatch) {
        const waitTime = floodMatch[1] ? Math.ceil(parseFloat(floodMatch[1])) : 30;
        console.log(`   \u23F3 Flood wait detected. Tunggu ${waitTime} detik...`);
        await new Promise(r => setTimeout(r, waitTime * 1000));
        continue;
      }
    }
    
    if (msgId < endId && isRunning) {
      // ✅ Gunakan fungsi randomDelay() yang sudah ada
      const delay = await randomDelay();
      console.log(`   \u23F3 Delay ${(delay/1000).toFixed(1)} detik (menghindari rate limit)...`);
    }
  }
  
  if (isRunning) {
    console.log('\n' + '='.repeat(40));
    console.log('\u2705 Scraping selesai!');
    generateReport(reportData);

    // Update scraping history
    updateHistory(reportData.parsedChannelId, reportData.startId, reportData.endId, reportData.deepLinks.length, false);
  } else {
    // ✅ Fix: Update history juga ketika bot berhenti di tengah
    updateHistory(reportData.parsedChannelId, reportData.startId, lastProcessedId, reportData.deepLinks.length, true);
  }
  
  try {
    const me = await client.getMe();
    const briefReport = `*Laporan Deep Link Scraping*\n\n` +
      `*Channel:* ${reportData.channelUsername}\n` +
      `*Range:* ID ${reportData.startId} - ID ${reportData.endId}\n` +
      `*Total Pesan:* ${reportData.totalMessages}\n` +
      `*Total Link:* ${reportData.totalLinks}\n` +
      `*Total Media:* ${reportData.totalMedia}\n` +
      `*Tanpa Media:* ${reportData.noMediaCount}\n` +
      `*Status:* ${reportData.stopped ? '⛔ BOT STOP' : '✅ SELESAI'}\n\n` +
      `_Report lengkap disimpan di file report.md_`;
    await client.sendMessage(me.id, { message: briefReport, parseMode: 'markdown' });
    console.log('\n\u2705 Laporan singkat telah dikirim ke Saved Messages.');
  } catch (e) {
    console.log('\n\u26A0\uFE0F Gagal kirim laporan ke Saved Messages:', e.message);
  }
  
  process.removeListener('SIGINT', safeExit);
  process.removeListener('SIGTERM', safeExit);
  
  rl.close();
  
}

module.exports = deepLinkScraper;
module.exports.parseChannelInput = parseChannelInput;