const fs = require('fs');
const path = require('path');
const { extractDeepLinks, generateStartMessage } = require('../utils/linkParser');
const { updateHistory, getAllChannels, getLastScrapedId, updateLastScrapedId } = require('../utils/scrapingHistory');
const config = require('../config');

const reportFileName = (typeof config.REPORT_FILE === 'string' && config.REPORT_FILE.trim()) ? config.REPORT_FILE : 'report.md';
const REPORT_FILE = path.resolve(__dirname, '..', reportFileName);

/**
 * Random delay antara konfigurasi MIN_DELAY-MAX_DELAY
 */
function randomDelay() {
  const minDelay = typeof config.MIN_DELAY === 'number' && !isNaN(config.MIN_DELAY) ? config.MIN_DELAY : 3000;
  const maxDelay = typeof config.MAX_DELAY === 'number' && !isNaN(config.MAX_DELAY) ? config.MAX_DELAY : 10000;
  const effectiveMin = Math.min(minDelay, maxDelay);
  const effectiveMax = Math.max(minDelay, maxDelay);
  const delay = Math.floor(Math.random() * (effectiveMax - effectiveMin + 1)) + effectiveMin;
  return new Promise((resolve) => setTimeout(() => resolve(delay), delay));
}

/**
 * Cek apakah pesan berisi media (foto/video)
 */
function hasMedia(message) {
  if (!message) return false;
  
  if (message.media) {
    const mediaType = message.media.className;
    return (
      mediaType === 'MessageMediaPhoto' ||
      mediaType === 'MessageMediaDocument' ||
      mediaType === 'MessageMediaVideo' ||
      mediaType === 'MessageMediaWebPage' ||
      mediaType === 'MessageMediaGeo' ||
      mediaType === 'MessageMediaContact' ||
      mediaType === 'MessageMediaPoll'
    );
  }
  return false;
}

/**
 * Escape HTML special characters to prevent HTML injection in report
 * Also escape markdown special characters for safe display
 */
function escapeForReport(str) {
  if (!str) return '';
  let escaped = String(str).replace(/[*_\[\]()~>#+\-=|{}.!]/g, '\\$&');
  escaped = escaped
    .replace(/&/g, '\u0026amp;')
    .replace(/</g, '\u0026lt;')
    .replace(/>/g, '\u0026gt;')
    .replace(/"/g, '\u0026quot;')
    .replace(/`/g, '\\`');
  return escaped;
}

/**
 * Generate report ke report.md
 */
function generateReport(reportData) {
  const report = `# Laporan Deep Link Scraping

---

## Informasi Scraping
- **Channel:** ${reportData.channelUsername || reportData.channelId || 'N/A'}
- **Range Pesan:** ID ${reportData.startId} - ID ${reportData.endId}
- **Tanggal:** ${new Date().toLocaleString('id-ID')}

---

## Statistik

| Metrik | Jumlah |
|--------|--------|
| Total Pesan Discrape | ${reportData.totalMessages} |
| Total Link Ditemukan | ${reportData.totalLinks} |
| Total Media (Foto/Video) | ${reportData.totalMedia} |
| Pesan yang Mengandung Deep Link | ${reportData.deepLinks.length} |
| Response tanpa Media | ${reportData.noMediaCount} |

---

## Detail Link

${reportData.deepLinks.length > 0 ? reportData.deepLinks.map((link, i) => `### ${i + 1}. Link
- **URL:** \`${escapeForReport(link.fullUrl)}\`
- **Bot:** @${escapeForReport(link.botUsername)}
- **Start Data:** \`${escapeForReport(link.startData)}\`
- **Response:** ${link.hasMedia ? '\u2705 Ada Media' : '\u274c Tidak Ada Media'}`).join('\n\n') : '**Tidak ada deep link ditemukan.**'}

---

## Status

${reportData.stopped ? '\u26a0\ufe0f **BOT STOP** - Ditemukan response tanpa media atau dihentikan user (Ctrl+C)' : '\u2705 **SELESAI** - Semua pesan berhasil discrape'}

---

*Report generated by UserTeleNode Bot*
`;

  fs.writeFileSync(REPORT_FILE, report, 'utf-8');
  console.log(`\n\u{1F4C4} Report telah disimpan ke: ${REPORT_FILE}`);
}

/**
 * Parse channel input to get proper entity identifier
 * Supports: @username, numeric ID (-100...), and t.me URLs
 * @param {string} input - Raw user input
 * @returns {string|number} Channel identifier suitable for getEntity
 */
function parseChannelInput(input) {
  if (!input) return null;
  
  let cleaned = String(input).trim();
  
  if (!cleaned) return null;
  
  // Handle t.me URLs
  if (cleaned.includes('t.me/')) {
    const match = cleaned.match(/t\.me\/([a-zA-Z0-9_]+)/);
    if (match) {
      cleaned = match[1];
    } else {
      const altMatch = cleaned.match(/t\.me\/(.+)/);
      cleaned = altMatch ? altMatch[1] : cleaned;
    }
    cleaned = cleaned.trim();
  }
  
  if (!cleaned) return null;
  
  // Check if it's a numeric channel ID (all digits with optional - prefix)
  const isNumericId = /^-?\d+$/.test(cleaned);
  
  if (isNumericId) {
    return parseInt(cleaned, 10);
  }
  
  if (!cleaned.startsWith('@')) {
    cleaned = '@' + cleaned;
  }
  
  return cleaned;
}

/**
 * Resolve channel entity from parsed ID with fallback handling
 * Specifically handles -100... channel IDs that may fail with standard getEntity
 * @param {TelegramClient} client - GramJS client
 * @param {string|number} parsedChannelId - Parsed channel identifier
 * @returns {Promise<Channel>} Resolved channel entity
 */
async function resolveChannelEntity(client, parsedChannelId) {
  // First, try standard getEntity
  try {
    return await client.getEntity(parsedChannelId);
  } catch (e) {
    // If getEntity fails and we have a numeric ID (especially -100...), use specialized resolution
    if (typeof parsedChannelId === 'number') {
      console.log(`   \u26A0\uFE0F getEntity gagal untuk numeric ID ${parsedChannelId}, mencoba resolusi khusus...`);
      console.log(`   Error: ${e.message}`);
      
      const idStr = String(parsedChannelId);
      let channelIdNum;
      
      // Extract actual channel ID from -100 prefix (Telegram channel encoding)
      // In Telegram: -100xxxxx means channel with internal ID = xxxx
      if (idStr.startsWith('-100')) {
        channelIdNum = parseInt(idStr.substring(4), 10);
      } else if (idStr.startsWith('-')) {
        channelIdNum = parseInt(idStr.substring(1), 10);
      } else {
        channelIdNum = parsedChannelId;
      }
      
      // Try to get the channel via alternative methods
      // Method 1: Try using the constructed peer
      try {
        // The channel ID we extracted might already be the right one
        // Use getEntity with the positive channel ID
        const positiveId = channelIdNum;
        console.log(`   Mencoba dengan channel ID positif: ${positiveId}`);
        return await client.getEntity(positiveId);
      } catch (e2) {
        console.log(`   \u26A0\uFE0F Metode 1 gagal: ${e2.message}`);
      }
      
      // Method 2: Try with explicitly constructed InputPeerChannel
      try {
        console.log(`   Mencoba InputPeerChannel dengan channelId=${channelIdNum}`);
        // We need accessHash, but we can try getting it from existing known entities
        // or by using getFullChannel if we can construct the peer
        const inputPeerChannel = {
          _: 'inputPeerChannel',
          channelId: channelIdNum,
          accessHash: 0n
        };
        return await client.getEntity(inputPeerChannel);
      } catch (e2) {
        console.log(`   \u26A0\uFE0F Metode 2 gagal: ${e2.message}`);
        
        // Final fallback: provide helpful error
        console.error(`\n\u274C Channel dengan ID ${parsedChannelId} tidak dapat diakses.`);
        console.log('\n   \u2139\uFE0F  Kemungkinan penyebab:');
        console.log('   • Anda bukan anggota channel tersebut');
        console.log('   • Channel bersifat private');
        console.log('   • ID channel tidak valid');
        console.log('   •Bot membutuhkan username channel (tanpa -100) sebagai gantinya');
        console.log('\n   💡 Saran: Coba gunakan username channel (contoh: @channelname)');
        console.log('   untuk menghindari masalah dengan format -100...');
        
        throw new Error(`Channel ${parsedChannelId} tidak dapat diakses`);
      }
    } else {
      // For usernames, re-throw original error
      throw e;
    }
  }
}

/**
 * Fetch the latest message ID for a channel from Telegram.
 * Returns null when channel is unavailable or has no messages.
 */
async function fetchLatestMessageId(client, channelName) {
  const parsedChannelId = parseChannelInput(channelName);
  if (!parsedChannelId) {
    return { latestMessageId: null, error: 'Invalid channel name' };
  }

  try {
    const channel = await client.getEntity(parsedChannelId);
    const messages = await client.getMessages(channel, { limit: 1 });
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return { latestMessageId: null, error: 'Tidak ada pesan' };
    }
    return { latestMessageId: messages[0].id, error: null };
  } catch (error) {
    return { latestMessageId: null, error: error.message || 'Tidak dapat diakses' };
  }
}

/**
 * Deep Link Scraper
 * @param {TelegramClient} client - Instance Telegram client
 */
async function deepLinkScraper(client, rl) {
  const reportData = {
    channelUsername: '',
    channelId: '',
    parsedChannelId: '',
    startId: 0,
    endId: 0,
    totalMessages: 0,
    totalLinks: 0,
    totalMedia: 0,
    noMediaCount: 0,
    deepLinks: [],
    stopped: false
  };

  let isRunning = true;
  let lastStartTimestamp = 0;
  let lastProcessedId = 0; // ✅ Track ID terakhir yang berhasil diproses secara realtime

  const safeExit = async () => {
    if (!isRunning) return;
    isRunning = false;
    
    console.log('\n\n\u26A0\uFE0F  Menerima sinyal berhenti...');
    console.log('\u{1F4CA} Merangkum laporan...');

    reportData.stopped = true;
    if (lastProcessedId > 0) {
      reportData.endId = lastProcessedId; // ✅ Fix: Gunakan ID terakhir yang sebenarnya diproses
    }
    generateReport(reportData);

    // Update scraping history if IDs are set
    if (reportData.startId > 0 && lastProcessedId > 0) {
      updateHistory(reportData.parsedChannelId, reportData.startId, lastProcessedId, reportData.deepLinks.length, true);
    }

    console.log('\u2705 Laporan telah disimpan.');
    console.log('\u{1F44B} Bot berhenti dengan aman.');
    
    try {
      await client.disconnect();
    } catch (e) {}

    process.removeListener('SIGINT', safeExit);
    process.removeListener('SIGTERM', safeExit);
    
    // ✅ Pastikan proses exit dengan aman setelah semua operasi IO selesai
    setTimeout(() => process.exit(0), 500);
  };

  process.on('SIGINT', safeExit);
  process.on('SIGTERM', safeExit);

  console.log('\n\u{1F517} Mode Deep Link Scraper');
  console.log('\u2500'.repeat(40));

  if (typeof rl?.question !== 'function') {
    console.error('\u274C Interface readline tidak tersedia.');
    process.exit(1);
  }

  // Tampilkan daftar channel history
  const savedChannels = getAllChannels();
  let sortedChannels = savedChannels;
  if (savedChannels.length > 0) {
    // ✅ Sortir channel berdasarkan terakhir diakses (terbaru di atas)
    // Buat copy array agar tidak mengubah data asli
    sortedChannels = [...savedChannels].sort((a, b) => {
      const dateA = new Date(a.lastScrapedAt);
      const dateB = new Date(b.lastScrapedAt);
      return isNaN(dateB.getTime()) ? -1 : isNaN(dateA.getTime()) ? 1 : dateB - dateA;
    });

    console.log('\n🔎 Mengambil status ID pesan terakhir untuk setiap channel history...');
    const channelStatuses = [];
    for (const channel of sortedChannels) {
      const result = await fetchLatestMessageId(client, channel.channelName);
      channelStatuses.push({
        ...channel,
        latestMessageId: result.latestMessageId,
        latestError: result.error
      });
    }

    console.log('\n📋 Daftar channel yang pernah discrape:');
    channelStatuses.forEach((ch, idx) => {
      const lastDate = new Date(ch.lastScrapedAt);
      const dateStr = isNaN(lastDate.getTime())
        ? 'Tidak diketahui'
        : `${lastDate.toLocaleDateString('id-ID')} ${lastDate.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}`;
      const latestMsg = ch.latestMessageId ? `Latest Msg ID: ${ch.latestMessageId}` : `Status: ${ch.latestError}`;
      const diff = ch.latestMessageId && ch.latestMessageId > ch.lastScrapedId
        ? `(+${ch.latestMessageId - ch.lastScrapedId} baru)`
        : '';
      console.log(`  ${idx + 1}. ${ch.channelName} | Last Scraped ID: ${ch.lastScrapedId} | ${latestMsg} ${diff}`);
    });
    console.log('\n💡 Ketik nomor channel untuk memilih dari history, atau masukkan username/channel baru.');
  }

  let channelInput = rl.question('\nMasukkan channel: ').trim();
  let parsedChannelId;

  if (channelInput === '') {
    console.log('❌ Channel tidak boleh kosong');
    process.exit(1);
  }

  // Cek apakah input adalah nomor dari daftar
  if (/^\d+$/.test(channelInput)) {
    const num = parseInt(channelInput, 10);
    if (savedChannels.length > 0 && num >= 1 && num <= sortedChannels.length) {
      const selectedChannel = sortedChannels[num - 1];
      parsedChannelId = parseChannelInput(selectedChannel.channelName);
      console.log(`✅ Memilih channel dari history: ${selectedChannel.channelName}`);
    } else {
      console.log('❌ Nomor channel tidak ada di daftar. Silakan masukkan channel secara manual.');
      channelInput = rl.question('\nMasukkan channel baru: ').trim();
      if (channelInput === '') {
        console.log('❌ Channel tidak boleh kosong');
        process.exit(1);
      }
      parsedChannelId = parseChannelInput(channelInput);
    }
  } else {
    parsedChannelId = parseChannelInput(channelInput);
  }

  if (!parsedChannelId) {
    console.error('\u274C Channel tidak boleh kosong.');
    console.log('   Masukkan username atau link channel yang valid.');
    process.exit(1);
  }

  reportData.parsedChannelId = parsedChannelId;
  
  console.log(`Target channel: ${parsedChannelId}`);
  
  // Cek channel terlebih dahulu
  console.log(`Mengecek channel ${parsedChannelId}...`);
  let channel;
  
  try {
    // Use the specialized resolver with fallback
    channel = await resolveChannelEntity(client, parsedChannelId);
  } catch (e) {
    console.error(`\u274C Channel ${parsedChannelId} tidak ditemukan atau tidak bisa diakses.`);
    console.log(`   Error: ${e.message}`);
    process.exit(1);
  }
  
  // Store channel info
  reportData.channelUsername = channel.username ? `@${channel.username}` : (typeof parsedChannelId === 'string' ? parsedChannelId : '');
  reportData.channelId = channel.id ? channel.id.toString() : (typeof parsedChannelId === 'number' ? parsedChannelId.toString() : 'N/A');
  
  console.log(`\u2705 Channel ditemukan: ${channel.title || channel.username || channel.id}`);
  
  // Dapatkan info pesan terakhir
  console.log('\nMendapatkan info pesan terakhir...');
  const messages = await client.getMessages(channel, { limit: 1 });
  if (!messages || !Array.isArray(messages) || messages.length === 0) {
    console.log('\u274C Tidak ada pesan di channel ini.');
    process.exit(1);
  }
   
  const maxMsgId = messages[0].id;
  console.log(`ID Pesan terakhir: ${maxMsgId}`);

  // Cek apakah ada history untuk channel ini
  const lastScrapedId = getLastScrapedId(parsedChannelId);
  let defaultStartId = 1;
  if (lastScrapedId) {
    defaultStartId = lastScrapedId + 1;
    console.log(`\n✅ ID terakhir yang discrape dari history: ${lastScrapedId}`);
    if (lastScrapedId >= maxMsgId) {
      console.log(`ℹ️ Semua pesan di channel sudah discrape sampai ID terbaru ${maxMsgId}`);
      console.log(`✅ Tidak ada pesan baru yang perlu discrape`);
      process.exit(0);
    }
    console.log(`   Terdapat ${maxMsgId - lastScrapedId} pesan baru sejak terakhir discrape.`);
    console.log(`👉 Default akan lanjut dari ID ${defaultStartId}`);
  } else {
    console.log('\nℹ️ Channel ini belum pernah discrape sebelumnya');
  }
  
  // Input range pesan with guards
  const startInput = rl.question(`\nMasukkan ID pesan awal (default: ${defaultStartId}): `).trim();
  let startId = parseInt(String(startInput), 10);
  
  if (isNaN(startId) || startId < 1 || startId > maxMsgId) {
    startId = defaultStartId;
  }
  
  // ✅ Warning jika user input ID dibawah history yang ada
  if (lastScrapedId && startId <= lastScrapedId) {
    console.log(`\n⚠️  PERINGATAN: ID ${startId} sudah pernah di scrape sebelumnya`);
    console.log(`   Ini akan menyebabkan scrape ulang pesan yang sudah diproses`);
  }
  
  const endInput = rl.question(`Masukkan ID pesan akhir (default: ${maxMsgId}): `).trim();
  let endId = parseInt(String(endInput), 10);
  
  if (isNaN(endId) || endId < startId || endId > maxMsgId) {
    endId = maxMsgId;
  }
  
  console.log(`\n✅ Range yang dipilih: ID ${startId} - ${endId}`);
  
  reportData.startId = startId;
  reportData.endId = endId;
  
  console.log('\n' + '='.repeat(40));
  console.log(`\u{1F680} Scraping dimulai...`);
  console.log(`   Channel: ${parsedChannelId}`);
  console.log(`   Range: ID ${startId} - ${endId}`);
  const minSec = (typeof config.MIN_DELAY === 'number' ? config.MIN_DELAY : 3000) / 1000;
  const maxSec = (typeof config.MAX_DELAY === 'number' ? config.MAX_DELAY : 10000) / 1000;
  console.log(`   Delay: ${minSec.toFixed(1)}-${maxSec.toFixed(1)} detik per pesan`);
  console.log('   Tekan Ctrl+C untuk berhenti dan generate report.');
  console.log('='.repeat(40));
  
  const totalToCheck = endId - startId + 1;

  if (totalToCheck <= 0) {
    console.log('\n❌ Range ID tidak valid');
    process.exit(1);
  }
  
  console.log(`\n✅ Akan memproses ${totalToCheck} pesan`);

  // ✅ Validasi konfigurasi delay
  if (typeof config.MIN_DELAY !== 'number' || config.MIN_DELAY < 0) {
    console.log('\n⚠️  MIN_DELAY tidak valid, menggunakan default 3000ms');
    config.MIN_DELAY = 3000;
  }
  if (typeof config.MAX_DELAY !== 'number' || config.MAX_DELAY < config.MIN_DELAY) {
    console.log('\n⚠️  MAX_DELAY tidak valid, menggunakan default 10000ms');
    config.MAX_DELAY = 10000;
  }
  
  for (let msgId = startId; msgId <= endId && isRunning; msgId++) {
    
      const progress = msgId - startId + 1;
      console.log(`\n\u{1F4E5} [${progress}/${totalToCheck}] Mengecek pesan ID: ${msgId}...`);
    
    try {
      const msgs = await client.getMessages(channel, { ids: [msgId] });
      
      if (!msgs || !Array.isArray(msgs) || msgs.length === 0) {
        console.log(`   \u23ED\uFE0F  Tidak ada pesan di ID ${msgId}.`);
        continue;
      }
      
      const message = msgs[0];
      if (!message || !message.id) {
        console.log(`   \u23ED\uFE0F  Pesan tidak valid di ID ${msgId}.`);
        // ✅ Tetap update ID terakhir bahkan jika pesan kosong / tidak valid
        lastProcessedId = msgId;
        continue;
      }
      
      reportData.totalMessages++;
      lastProcessedId = msgId; // ✅ Update HANYA setelah pesan BERHASIL di proses
      
      if (hasMedia(message)) {
        reportData.totalMedia++;
        console.log(`   \u{1F5BC}\uFE0F  Pesan mengandung media.`);
      }
      
      const messageText = message.text || '';
      if (messageText) {
        console.log(`   \u{1F4DD} Text: ${messageText.substring(0, 100)}${messageText.length > 100 ? '...' : ''}`);
      }
      
      const deepLinks = extractDeepLinks(messageText);
      
      if (deepLinks.length > 0) {
        console.log(`   \u{1F517} Ditemukan ${deepLinks.length} deep link!`);
        reportData.totalLinks += deepLinks.length;
        
        for (const link of deepLinks) {
          console.log(`   \u21B3 Bot: @${link.botUsername}`);
          console.log(`   \u21B3 Start Data: ${link.startData}`);
          
          let botPeer;
          try {
            botPeer = await client.getEntity(link.botUsername);
            console.log(`   \u2705 Bot ditemukan: ${botPeer.firstName || botPeer.username}`);
          } catch (e) {
            console.log(`   \u26A0\uFE0F Bot @${link.botUsername} tidak ditemukan. Skip.`);
            continue;
          }
          
          const startMessage = generateStartMessage(link.botUsername, link.startData);
          console.log(`   \u{1F4E4} Mengirim: ${startMessage}`);
          
          try {
            await client.sendMessage(botPeer, { message: startMessage });
            lastStartTimestamp = Date.now();
            console.log(`   \u23F3 Menunggu response dari bot...`);
            
            try {
              const botMessages = await client.getMessages(botPeer, { limit: 5 });
              if (!botMessages || !Array.isArray(botMessages)) {
                botMessages = [];
              }
              
              const recentMessages = botMessages.filter(msg => {
                if (!msg || !msg.date) return false;
                const msgTimestamp = typeof msg.date === 'number' ? msg.date * 1000 : new Date(msg.date).getTime();
                const isAfterStart = msgTimestamp > lastStartTimestamp;
                const senderId = msg.fromId ? (msg.fromId.userId || msg.fromId.channelId || msg.fromId.chatId) : null;
                const isFromBot = senderId && String(senderId) === String(botPeer.id);
                return isAfterStart && isFromBot;
              });
              
              const response = recentMessages.length > 0 ? recentMessages[0] : null;
              
              if (response) {
                const hasMediaResponse = hasMedia(response);
                link.hasMedia = hasMediaResponse;
                
                if (hasMediaResponse) {
                  console.log(`   \u2705 Bot response dengan media.`);
                  reportData.totalMedia++;
                } else {
                  console.log(`   \u274C Bot response TANPA media!`);
                  console.log(`   Response text: ${(response.text || 'N/A').substring(0, 100)}`);
                  
                  reportData.noMediaCount++;
                  
                  console.log('\n' + '='.repeat(40));
                  console.log('\u26D4 BOT STOP - Response bot tidak mengandung media!');
                  console.log('='.repeat(40));
                  
                  // ✅ Update ID terakhir SEBELUM exit
                  lastProcessedId = msgId;

                  isRunning = false;
                  reportData.stopped = true;
                  reportData.endId = msgId;
                  link.hasMedia = false;
                  reportData.deepLinks.push(link);

                  // ✅ Gunakan safeExit untuk exit secara aman dan konsisten
                  safeExit();
                  return;
                }
              } else {
                console.log(`   \u26A0\uFE0F Tidak ada response dari bot.`);
                link.hasMedia = false;
              }
            } catch (e) {
              console.log(`   \u26A0\uFE0F Gagal cek response bot: ${e.message}`);
              link.hasMedia = false;
            }
            
            if (!reportData.stopped) {
              reportData.deepLinks.push(link);
            }
            
          } catch (e) {
            console.log(`   \u274C Gagal kirim /start ke bot: ${e.message}`);
            link.hasMedia = false;
            reportData.deepLinks.push(link);
          }
        }
      }
      
      
    } catch (e) {
      console.log(`   \u274C Error: ${e.message}`);
      
      const floodMatch = e.message.match(/wait of ([\d.]+)/i) ||
                         e.message.match(/flood[_ ]wait[_ ]?(\d+)/i) ||
                         e.message.match(/floodwait/i);
      if (floodMatch) {
        let waitTime = floodMatch[1] ? Math.ceil(parseFloat(floodMatch[1])) : 30;
        waitTime = Math.min(waitTime, 300); // Cap at 5 minutes
        console.log(`   \u23F3 Flood wait detected. Tunggu ${waitTime} detik...`);
        await new Promise(r => setTimeout(r, waitTime * 1000));
        continue;
      }
    }
    
    if (msgId < endId && isRunning) {
      // ✅ Gunakan fungsi randomDelay() yang sudah ada
      const delay = await randomDelay();
      console.log(`   \u23F3 Delay ${(delay/1000).toFixed(1)} detik (menghindari rate limit)...`);
    }
  }
  
  if (isRunning) {
    console.log('\n' + '='.repeat(40));
    console.log('\u2705 Scraping selesai!');
    generateReport(reportData);

    // Update scraping history
    updateHistory(reportData.parsedChannelId, reportData.startId, reportData.endId, reportData.deepLinks.length, false);
  } else {
    // ✅ Fix: Update history juga ketika bot berhenti di tengah
    updateHistory(reportData.parsedChannelId, reportData.startId, lastProcessedId, reportData.deepLinks.length, true);
  }
  
  try {
    const me = await client.getMe();
    const briefReport = `*Laporan Deep Link Scraping*\n\n` +
      `*Channel:* ${reportData.channelUsername}\n` +
      `*Range:* ID ${reportData.startId} - ID ${reportData.endId}\n` +
      `*Total Pesan:* ${reportData.totalMessages}\n` +
      `*Total Link:* ${reportData.totalLinks}\n` +
      `*Total Media:* ${reportData.totalMedia}\n` +
      `*Tanpa Media:* ${reportData.noMediaCount}\n` +
      `*Status:* ${reportData.stopped ? '⛔ BOT STOP' : '✅ SELESAI'}\n\n` +
      `_Report lengkap disimpan di file report.md_`;
    await client.sendMessage(me.id, { message: briefReport, parseMode: 'markdown' });
    console.log('\n\u2705 Laporan singkat telah dikirim ke Saved Messages.');
  } catch (e) {
    console.log('\n\u26A0\uFE0F Gagal kirim laporan ke Saved Messages:', e.message);
  }
  
  process.removeListener('SIGINT', safeExit);
  process.removeListener('SIGTERM', safeExit);
  
  rl.close();
  
}

/**
 * Web scraper function that accepts parameters directly (for web interface)
 */
async function webScraper(client, channel, startId = null, endId = null, progressCallback = null) {
  const reportData = {
    channelUsername: '',
    channelId: '',
    parsedChannelId: '',
    startId: 0,
    endId: 0,
    totalMessages: 0,
    totalLinks: 0,
    totalMedia: 0,
    noMediaCount: 0,
    deepLinks: [],
    stopped: false
  };

  let isRunning = true;
  let lastStartTimestamp = 0;
  let lastProcessedId = 0;

  const safeExit = async () => {
    if (!isRunning) return;
    isRunning = false;

    console.log('\n\n\u26A0\uFE0F  Scraping stopped...');
    console.log('\u{1F4CA} Generating report...');

    if (progressCallback) {
      progressCallback({
        type: 'status',
        status: 'generating_report',
        message: 'Generating report...'
      });
    }

    reportData.stopped = true;
    if (lastProcessedId > 0) {
      reportData.endId = lastProcessedId;
    }
    generateReport(reportData);

    if (reportData.startId > 0 && lastProcessedId > 0) {
      updateHistory(reportData.parsedChannelId, reportData.startId, lastProcessedId, reportData.deepLinks.length, true);
    }

    console.log('\u2705 Report saved.');
    console.log('\u{1F44B} Scraping completed safely.');

    if (progressCallback) {
      progressCallback({
        type: 'completed',
        reportData,
        message: 'Scraping completed!'
      });
    }

    try {
      await client.disconnect();
    } catch (e) {}
  };

  try {
    const parsedChannelId = parseChannelInput(channel);
    if (!parsedChannelId) {
      throw new Error('Invalid channel format');
    }

    reportData.parsedChannelId = parsedChannelId;

    console.log(`Target channel: ${parsedChannelId}`);

    console.log(`Checking channel ${parsedChannelId}...`);
    let channelEntity;

    try {
      channelEntity = await resolveChannelEntity(client, parsedChannelId);
    } catch (e) {
      throw new Error(`Channel ${parsedChannelId} not found or inaccessible: ${e.message}`);
    }

    reportData.channelUsername = channelEntity.username ? `@${channelEntity.username}` : (typeof parsedChannelId === 'string' ? parsedChannelId : '');
    reportData.channelId = channelEntity.id ? channelEntity.id.toString() : (typeof parsedChannelId === 'number' ? parsedChannelId.toString() : 'N/A');

    console.log(`\u2705 Channel found: ${channelEntity.title || channelEntity.username || channelEntity.id}`);

    console.log('\nGetting latest message info...');
    const messages = await client.getMessages(channelEntity, { limit: 1 });
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      throw new Error('No messages in this channel.');
    }

    const maxMsgId = messages[0].id;
    console.log(`Latest message ID: ${maxMsgId}`);

    const lastScrapedId = getLastScrapedId(parsedChannelId);
    let defaultStartId = 1;
    if (lastScrapedId) {
      defaultStartId = lastScrapedId + 1;
      console.log(`\n✅ Last scraped ID from history: ${lastScrapedId}`);
      if (lastScrapedId >= maxMsgId) {
        console.log(`ℹ️ All messages up to latest ID ${maxMsgId} have been scraped`);
        console.log(`✅ No new messages to scrape`);
        return;
      }
      console.log(`   There are ${maxMsgId - lastScrapedId} new messages since last scrape.`);
      console.log(`👉 Will continue from ID ${defaultStartId}`);
    } else {
      console.log('\nℹ️ This channel has never been scraped before');
    }

    let startIdNum = startId ? parseInt(startId, 10) : defaultStartId;
    if (isNaN(startIdNum) || startIdNum < 1 || startIdNum > maxMsgId) {
      startIdNum = defaultStartId;
    }

    if (lastScrapedId && startIdNum <= lastScrapedId) {
      console.log(`\n⚠️  WARNING: ID ${startIdNum} has been scraped before`);
      console.log(`   This will cause re-scraping of already processed messages`);
    }

    let endIdNum = endId ? parseInt(endId, 10) : maxMsgId;
    if (isNaN(endIdNum) || endIdNum < startIdNum || endIdNum > maxMsgId) {
      endIdNum = maxMsgId;
    }

    console.log(`\n✅ Selected range: ID ${startIdNum} - ${endIdNum}`);

    reportData.startId = startIdNum;
    reportData.endId = endIdNum;

    console.log('\n' + '='.repeat(40));
    console.log(`\u{1F680} Scraping started...`);
    console.log(`   Channel: ${parsedChannelId}`);
    console.log(`   Range: ID ${startIdNum} - ${endIdNum}`);
    const minSec = (typeof config.MIN_DELAY === 'number' ? config.MIN_DELAY : 3000) / 1000;
    const maxSec = (typeof config.MAX_DELAY === 'number' ? config.MAX_DELAY : 10000) / 1000;
    console.log(`   Delay: ${minSec.toFixed(1)}-${maxSec.toFixed(1)} second per message`);
    console.log('='.repeat(40));

    const totalToCheck = endIdNum - startIdNum + 1;

    if (totalToCheck <= 0) {
      throw new Error('Invalid ID range');
    }

    console.log(`\n✅ Will process ${totalToCheck} messages`);

    if (progressCallback) {
      progressCallback({
        type: 'started',
        channel: parsedChannelId,
        startId: startIdNum,
        endId: endIdNum,
        totalMessages: totalToCheck,
        message: `Started scraping ${totalToCheck} messages from ${parsedChannelId}`
      });
    }

    for (let msgId = startIdNum; msgId <= endIdNum && isRunning; msgId++) {
      const progress = msgId - startIdNum + 1;
      console.log(`\n\u{1F4E5} [${progress}/${totalToCheck}] Checking message ID: ${msgId}...`);

      if (progressCallback) {
        progressCallback({
          type: 'progress',
          currentMessage: msgId,
          progress,
          totalMessages: totalToCheck,
          message: `Processing message ${msgId} (${progress}/${totalToCheck})`
        });
      }

      try {
        const msgs = await client.getMessages(channelEntity, { ids: [msgId] });

        if (!msgs || !Array.isArray(msgs) || msgs.length === 0) {
          console.log(`   Message ID ${msgId} not found or deleted`);
          lastProcessedId = msgId;
          continue;
        }

        const message = msgs[0];
        reportData.totalMessages++;

        const deepLinks = extractDeepLinks(message.message || '');

        if (deepLinks.length > 0) {
          console.log(`   Found ${deepLinks.length} deep link(s)`);

          if (progressCallback) {
            progressCallback({
              type: 'links_found',
              messageId: msgId,
              linksCount: deepLinks.length,
              message: `Found ${deepLinks.length} deep link(s) in message ${msgId}`
            });
          }

          for (const link of deepLinks) {
            reportData.totalLinks++;
            console.log(`   Processing link: ${link.fullUrl}`);

            if (progressCallback) {
              progressCallback({
                type: 'processing_link',
                messageId: msgId,
                link: link.fullUrl,
                message: `Processing link: ${link.fullUrl}`
              });
            }

            try {
              const response = await client.invoke({
                _: 'messages.startBot',
                bot: await client.getInputEntity(link.botUsername),
                peer: await client.getInputEntity(link.botUsername),
                startParam: link.startData,
                randomId: Math.floor(Math.random() * 0x100000000)
              });

              if (response && response.updates) {
                let hasMedia = false;
                for (const update of response.updates) {
                  if (update.message && hasMedia(update.message)) {
                    hasMedia = true;
                    reportData.totalMedia++;
                    break;
                  }
                }

                if (hasMedia) {
                  console.log(`   ✅ Response has media`);
                  if (progressCallback) {
                    progressCallback({
                      type: 'link_success',
                      messageId: msgId,
                      link: link.fullUrl,
                      hasMedia: true,
                      message: `✅ Link ${link.fullUrl} has media`
                    });
                  }
                } else {
                  console.log(`   ❌ Response has no media`);
                  reportData.noMediaCount++;
                  if (progressCallback) {
                    progressCallback({
                      type: 'link_success',
                      messageId: msgId,
                      link: link.fullUrl,
                      hasMedia: false,
                      message: `❌ Link ${link.fullUrl} has no media`
                    });
                  }
                  if (reportData.noMediaCount >= 3) {
                    console.log(`   \u26A0\uFE0F 3 responses without media, stopping...`);
                    if (progressCallback) {
                      progressCallback({
                        type: 'stopping',
                        reason: 'too_many_no_media',
                        message: 'Stopping due to 3 responses without media'
                      });
                    }
                    isRunning = false;
                    break;
                  }
                }

                reportData.deepLinks.push({
                  ...link,
                  hasMedia
                });
              }
            } catch (e) {
              console.log(`   Error processing link: ${e.message}`);
              if (progressCallback) {
                progressCallback({
                  type: 'link_error',
                  messageId: msgId,
                  link: link.fullUrl,
                  error: e.message,
                  message: `Error processing link ${link.fullUrl}: ${e.message}`
                });
              }
            }
          }
        } else {
          console.log(`   No deep links found`);
        }

        lastProcessedId = msgId;

        if (msgId < endIdNum) {
          console.log(`   Waiting ${Math.round(await randomDelay() / 1000)} seconds...`);
        }

      } catch (e) {
        console.log(`   Error processing message ${msgId}: ${e.message}`);
        lastProcessedId = msgId;
        if (progressCallback) {
          progressCallback({
            type: 'message_error',
            messageId: msgId,
            error: e.message,
            message: `Error processing message ${msgId}: ${e.message}`
          });
        }
      }
    }

    console.log('\n' + '='.repeat(40));
    console.log('\u2705 Scraping completed!');
    generateReport(reportData);

    if (reportData.startId > 0 && lastProcessedId > 0) {
      updateHistory(reportData.parsedChannelId, reportData.startId, lastProcessedId, reportData.deepLinks.length, false);
    }

    if (progressCallback) {
      progressCallback({
        type: 'completed',
        reportData,
        message: 'Scraping completed successfully!'
      });
    }

    try {
      await client.disconnect();
    } catch (e) {}

  } catch (error) {
    console.error('Scraping error:', error.message);
    throw error;
  }
}

module.exports = deepLinkScraper;
module.exports.parseChannelInput = parseChannelInput;
module.exports.webScraper = webScraper;